name: workout_pro
description: A minimalist cross-platform workout tracker
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  go_router: ^14.8.1  
  firebase_core: ^3.13.0           
  firebase_auth: ^5.5.2           
  google_sign_in: ^6.1.5
  provider: ^6.1.4
  flutter_animate: ^4.5.2
  cloud_firestore: ^5.6.6
  intl: ^0.19.0
  flutter_gherkin: ^2.0.0
  
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.1  
  fl_chart: ^0.66.0
  



dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  gherkin: ^3.1.0
  vm_service: ^15.0.0
  webdriver: ^3.1.0
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  pie_chart: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  
    
   

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
